### ISSUE TITLE
Allow concatenation of strings and variables

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#113]
__Challenge__:  We are using xenia to pull data from statistics documents that have a regular form:

```
user_statistics.statstics.comments.[dimension].[CommentStatus].[Field]
```

For example, this matches all users in the section.opinions dimension with ten or more comments that have been SystemFlagged.

```
        {
        	"$match": {
        		"statstics.comments.section.opinions.SystemFlagged.count": {"$gte": 10}
        	}
        },
```

We would like to make this a lot more dynamic by being able to pass in these concepts as variables and embed them like so:

```
        {
        	"$match": {
        		"statstics.comments.{dimension}.{commentStatus}.{value}": {"$gte": 10}
        	}
        },
```

The current variable system doesn't seem to allow this, as the ```#var``` syntax doesn't permit concatenation.

**Comment by ardan-bkennedy** [comment]
The var system is only for values at this time. You want to substitute field names as well. Once I am done with masking I will move to this feature.
