### ISSUE TITLE
Discussion - expression operators

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#114]
We need to be able to evaluate basic expressions at query execution time.  How is this best done?

**Comment by jde** [comment]
First use case is to be able to query for all documents "in the last [duration]", aka, all users who have commented in sports _in the last month._

Mapping this concept to [golang's time.Duration](https://golang.org/pkg/time/#Duration) seems to most efficient way to proceed:

```
    #[n]:seconds:Ago
    #[n]:minutes:Ago
    #[n]:days:Ago
    #[n]:hours:Ago
```

**Comment by ardan-bkennedy** [comment]
This must be done in the service, manipulating the query command prior to sending it to MongoDB. That is power Xenia brings. Your idea of the following expression

```#3600:secondsAgo```

This is brilliant because we can generate a time value that is 3600 seconds ago.

**Comment by ardan-bkennedy** [comment]
I would follow the current format
```
 #[n]:agoSeconds
 #[n]:agoMinutes
 #[n]:agoDays
 #[n]:agoHours
```

Or just keep everything in seconds and only use ago

```
#3600:ago
```

**Comment by ardan-bkennedy** [comment]
We will need a cheat sheet soon or time spent on the wiki for xenia.

**Comment by ardan-bkennedy** [comment]
Actually, the dev UI will need this information so maybe we need to store it in a collection for use by the UI?

**Comment by jde** [comment]
After a bit of reflection, it seems like having durations that are represented in strings that need to be provided by the front end will just introduce more code.  

I would say we should use ms, but ISODates only hold second specificity, I believe.  So let's go with seconds:

```
  #3600:ago // an hour
```

**Comment by jde** [comment]
A xenia cheat sheet is definitely needed. :)

**Comment by ardan-bkennedy** [comment]
+1 on this

```
#3600:ago // an hour
```

**Comment by jde** [comment]
the "ago" operator is nice and compact but begs the question of the duration.  I would stick with:

```
  #3600:secondsAgo
```

For self-documenting clarity.

**Comment by ardan-bkennedy** [comment]
ago is connected with time. How else can ago be used?
Def: (used after a measurement of time) before the present; earlier.
the word `since` is a synonym.

**Comment by jde** [comment]
Ago is always connected with time, but does not include the duration.  A dev seeing simply "ago" in a query would no immediately understand that the specific concept is _seconds_Ago. 

"Since" in common parlance is used with a fixed point in the time in past (or at least in my experience).  Aka, since July, 13th 1978.  The construction "since 3600" for me doesn't cleanly give the meaning of an expression resolving to a timestamp from 3600 seconds ago.

**Comment by ardan-bkennedy** [comment]
We could follow the Go convention and tag the number with a duration.

```"#ago:3600s"```

```
"ns": int64(Nanosecond),
"us": int64(Microsecond),
"µs": int64(Microsecond), // U+00B5 = micro symbol
"μs": int64(Microsecond), // U+03BC = Greek letter mu
"ms": int64(Millisecond),
"s":  int64(Second),
"m":  int64(Minute),
"h":  int64(Hour),
```

**Comment by ardan-bkennedy** [comment]
Decided to use `time:value`. This will allow us to go forward and backwards in time.

```
#time:0  -> Current date/time
#time:-3600  -> 3600 seconds in the past
#time:3m  -> 3 minutes in the future.
```
