### ISSUE TITLE
What is the most efficient way to get document counts on a query_set?

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#116]
__Challenge__ Query_sets are the foundation of User Groups for our front end.  As such, we are going to need to provide some meta data about them efficiently.

The first thing we'd like to show on the fe is a _count_ of the number of documents returned.  In the current paradigm, this is impossible without some sort of proxy.

__One Solution__: create a request parameter (aka, .../1.0/exec/myquery?count=_id) that:
* removes any limit statements
* removes any skip statements
* appends a pipeline operation to the end of the query that will give the distinct count of documents returned based on that field

The only other solution I can see would be to maintain a separate service that proxies these queries, loads them, does the manipulations, dynamically executes them and does the counting that way.

**Comment by ardan-bkennedy** [comment]
This might be a case where we add a field to the query set to ask only for counts.

**Comment by ardan-bkennedy** [comment]
are you paging so you need the total? Why not add the count query first and return both in the result set?

**Comment by riley** [comment]
the front end can proxy the queries. You would just have another action in `actions/index.js` that would gather the state, and append a `$group` step to the built query.

**Comment by riley** [comment]
referencing for github hooks https://github.com/coralproject/cay/issues/108
