### ISSUE TITLE
Add flags parameter to log.Init

### ISSUE THREAD

**Issue by impronunciable** [coralproject/xenia#117]
While building `xenia` I got an error on this line https://github.com/coralproject/xenia/blob/master/cmd/xenia/main.go#L51 because now `kit/log` needs a third parameter called `flags`. I managed to make it work adding a `0` as the third parameter (I have no idea what it means, we should take a look).

**Comment by ardan-bkennedy** [comment]
This means you are not using the vendored version of log when building?

**Comment by ardan-bkennedy** [comment]
I updated master with the latest code for kit. Let's make sure @impronunciable you have the vendor flag set when performing a build for the future.
