### ISSUE TITLE
missing headers on saving a query

### ISSUE THREAD

**Issue by riley** [coralproject/xenia#125]
## What?
Saving a query_set to xenia is successful (responds with a `204`), but since the response does not have the `Access-Control-Allow-Origin` header, the browser views it as a failure because of the CORS protocol apparently. 

![screen shot 2016-03-31 at 10 26 51 am](https://cloud.githubusercontent.com/assets/282503/14182994/238e317c-f72b-11e5-9ee0-8784513725de.png)

## How to fix?

Send the `Access-Control-Allow-Origin` header on the response to the `PUT` request.

**Comment by ardan-bkennedy** [comment]
We fixed the bug with the CORS header missing in these cases.
