### ISSUE TITLE
Enable default values for variables

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#138]
The current behavior of Xenia is to throw errors if variables aren't present as GET params. 

We need to be able to default the variables in the case that they aren't present.

Flagship use case is skip and limit.  These variables should both default to 0, which will provide the complete result set.  Adding them as params effectively 'turns on pagination.'  This is very helpful in a few contexts and needing to hard code ?skip=0&limit=0 for the full set is going to cause issues and is inelegant.

**Comment by ardan-bkennedy** [comment]
If a parameter is provided and no regex validation is applied and no variable was passed in, the default value set with the parameter is used.

https://github.com/coralproject/xenia/blob/master/pkg/exec/params.go#L37
