### ISSUE TITLE
Allow limit to be equal to 0

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#144]
Limit of 0 for mongo is valid for "no limit"

https://xenia_stg.coralproject.net/1.0/exec/trust_search_576a7e2e294626000644b954?limit=0

returns 

```
{"results":{"commands":[{"$sort":{"statistics.comments.all.all.reply_count":-1}},{"$skip":0},{"$limit":0},{"$project":{"avatar":true,"name":true,"statistics.comments":true}}],"error":"the limit must be positive"}}
```

Enable limit of 0;

**Comment by ardan-bkennedy** [comment]
In the aggregation engine you can't have a limit of 0
https://docs.mongodb.com/manual/reference/operator/aggregation/limit/

I think that only applies to cursors
https://docs.mongodb.com/manual/reference/method/cursor.limit/
