### ISSUE TITLE
Dynamic Query Execution via http endpoint

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#34]
__Challenge__: Front end applications will need the ability to compose custom queries.  

__Solution__: Build a dynamic query execution feature and expose it over http.  This feature should support all mongo aggregation pipeline commands.

__Spec__:
Input: 
* query: (required) aggregation query in json format
* explain: (optional) if present, run pipeline with explain option*

Output: 
* response code: 
* data returned from server
* as much error information as we can get*
* (optional) output of explain option if present in input*

__Note__: * this feature shifts the query development process completely to a front end interface.  It will be essential to pass query errors and explain details through to the client so that we can understand what is happening on the server.  Logging should also include a window into this information.

**Comment by ardan-bkennedy** [comment]
@jde Please view the TestQueryExecCustom test. We can now post a Set document for execution. Basic validation is applied to the document before execution.

**Comment by ardan-bkennedy** [comment]
done
