### ISSUE TITLE
Pre/Post pipeline operations

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#35]
__Challenge__: We need to be able to flexibly execute pipelines on subsets of of our dataset.  This is best accomplished via a series of $match or other commands before the pipeline.  We will also need to be able to sort/limit/etc... the response set flexibly.  These problems can be solved by operations executed after the meat of the query.

__Solution__: Accept two arrays of operations when executing a query.  Prepend one to the operations array and append the other to the end before executing the pipeline.

__Spec__: Augment the query execution endpoints 

Input:
* query: (as is, the name of the query to run)
* pre-ops: (optional) json array of operations to be prepended
* post-ops: (optional) json array of operations to be appended
* ... other params

Output:
* unchanged other than possibly appending the pre/post ops to the meta data

__Note__: pre and post ops should be compatible with dynamic queries #34

**Comment by ardan-bkennedy** [comment]
This issue has been coded based on this set of PR's

[PR 44](https://github.com/coralproject/xenia/pull/44)
[PR 46](https://github.com/coralproject/xenia/pull/46)
[PR 47](https://github.com/coralproject/xenia/pull/47)
[PR 48](https://github.com/coralproject/xenia/pull/48)

**Comment by ardan-bkennedy** [comment]
Need CLI support to CRUD script documents in the database.
