### ISSUE TITLE
CRUD support for both the Web Service and CLI tooling

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#36]
__Challenge__: We are building front end tools that will effectively act as management interfaces for query_sets.  

__Solution__: Publish http endpoints for the CRUD features already present in the CLI tool. We also need to add endpoints for the new Script document.

__Spec__:
REST style (GET, PUT, POST, DELETE) to /xenia/query... endpoints

**Comment by ardan-bkennedy** [comment]
Edited the issue to include Script documents and CLI support.

**Comment by ardan-bkennedy** [comment]
This is now complete
