### ISSUE TITLE
ISODates 

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#39]
I've been trying for a long time to find the proper escaping patterns to make this work:
```
{
   "name":"comments_per_day",
   "desc":"comments per day",
   "enabled":true,
   "params":null,
   "queries":[
      {
         "name":"comments_per_day",
         "type":"pipeline",
         "collection":"comment",
         "return":true,
         "has_date":true,
         "scripts":[


            "{ \"$match\": { \"date_created\": {\"$gt\" : \"ISODate(\\\"#start_date#T00:00:00Z\\\")\"} } }",
            "{ \"$match\": { \"date_created\": {\"$lt\" : \"ISODate(\\\"#end_date#T00:00:00Z\\\")\"} } }",
            "{ \"$group\": { \"_id\": { \"day\": { \"$dayOfMonth\": \"$date_created\" }, \"month\": { \"$month\": \"$date_created\" }, \"year\": { \"$year\": \"$date_created\" } }, \"comments\": { \"$sum\": 1 } } }"

         ]
      }
   ]
}
```

I've tried many variations on how to work with the ISODate() syntax but can't get xenia to produce the correct syntax that mongo expects.

I've tried with and without the "has_date":true flag.  has_date seems to strip out the ISODate() call all together, which I don't think is desired behavior.

Ultimately, these escaping patterns are very challenging to work with.  Simplification would save a lot of time and frustration on the developer's side.

This query is loaded into xenia:

* Connect xenia to 52.23.154.37:27017/coral 
* Execute http://localhost:4000/1.0/query/comments_per_day/exec?start_date=2015_01_01&end_date=2016_01_01

**Comment by ardan-bkennedy** [comment]
Fixed Merged [https://github.com/coralproject/xenia/pull/40]
