### ISSUE TITLE
Data to populate controls/filters for explorer view

### ISSUE THREAD

**Issue by colinmegill** [coralproject/xenia#41]
After some discussion:

* We're going to have to make an 'init' call for the data explorer view to find min max ranges for inputs with continuous data (dates and comment counts, for example). The alternative, not doing this, wouldn't be a great experience - users wouldn't know what data was available to query and the inputs would all be empty text input fields
* Inevitably, more fields will be added in the future
* It is more extensible if we don't hard code these in the UI since we have to make init calls anyway to populate them - better to store a schema in the database. This will mean making only one call from the explorer view such as `this.populateControls()` in `componentWillMount`. 

As a bonus, though it's not in the roadmap now, this design does not preclude the addition of custom filter fields in the future if it becomes desirable. 

cc @jde

**Comment by colinmegill** [comment]
I'm going to leave the rest as a comment here to kick off discussion. Certainly, we're looking at a collection, what's in it is up for grabs:

```
[
  {
    field: "ApproveDate", 
    min: millisecondsSinceEpoch, 
    max: millisecondsSinceEpoch 
  },
  { ... },
  ...
]
```

We could store what input we'd like it to be - like `type: "dropdown"` but we can also sniff that out on the client. Not as important.

**Comment by riley** [comment]
@ardan-bkennedy @gabelula @samshub about making an init endpoint.

**Comment by jde** [comment]
Let's put the conversation here on hold and develop the data packet that we want to generate in this thread: https://github.com/coralproject/cay/issues/22

@colinmegill, could you transcribe your thoughts above into the cay issue or the attached wiki page?

I'm going to close this discussion here as this may be a better fit for Pillar, our custom service layer.  Once we have designed the data that we're asking for we can reopen a clean issue in the best place.
