### ISSUE TITLE
Propose to consolidate endpoints

### ISSUE THREAD

**Issue by riley** [coralproject/xenia#54]
## What?!

Currently, for the front end to display data, many requests have to be made:

1. A request to `/1.0/query` for the list of names of `query_sets`. A JSON string is returned, looking something like `["basic", "comments_by_asset", "comments_by_user"...]`
2. Info for _each_ query must be made via a separate request i.e. `/1.0/query/basic` & `/1.0/query/comment_by_asset` ... _n_ times before the UI becomes responsive.

## How to fix

I propose to just return all the available data needed to execute the `query_set` on the `/1.0/query` endpoint instead of just the name in an array. This would save a ton of requests and boilerplate in the front-end code. We would still retain the `/1.0/query/<query_set_name>` endpoint for the `query_set` editor to be built later. So `/1.0/query` becomes:

```
[
{
   "name":"comments_by_asset",
   "desc":"Shows comments on and asset, sorted by date desc",
   "enabled":true,
   "params":null,
   "queries":[
      {
         "name":"comments_by_asset",
         "type":"pipeline",
         "collection":"nyt_coral_comments",
         "return":true,
         "scripts":[

            "{ \"$match\": { \"asset_id\": #asset_id# } }",
            "{ \"$sort\": { \"createDate\": -1 } }"

         ]
      }
   ]
},
{
   "name":"comments_by_user",
   "desc":"Shows comments by user, sorted by date desc",
   "enabled":true,
   "params":null,
   "queries":[
      {
         "name":"comments_by_user",
         "type":"pipeline",
         "collection":"nyt_coral_comments",
         "return":true,
         "scripts":[

            "{ \"$match\": { \"user_id\": #user_id# } }",
            "{ \"$sort\": { \"createDate\": -1 } }"

         ]
      }
   ]
}
...
]
```

**Comment by ardan-bkennedy** [comment]
Yea, we can do that but what if there are 100's or 1000's of query sets. That is a lot of data to return?

**Comment by jde** [comment]
Good thought.  The tagging concept of #55 will keep this efficient. 

I think we can also leave off the queries subdocument and still get all the info we need. @riley, can you confirm?

**Comment by riley** [comment]
We need the entire document to execute a `query_set` right? If the queries subdoc was missing, I'd still have to make another call before execution. I'd love to be able to make calls to any endpoint after the initial load of the query_set definitions.

I'm definitely interested in loading by category, but it seems like a preoptimization. We don't know if it's going to be slow or not, I would think it's just doing a `find({})` on the query_sets collection.

**Comment by ardan-bkennedy** [comment]
I am in training but between breaks coding. Need to make sure tests are in place. This is a breaking API change

**Comment by jde** [comment]
@riley the name of the query_set is on the outside of the queries subdocument, so you wouldn't need to make multiple calls.

**Comment by jde** [comment]
@riley, on the pre-optimization comment, we already have a use case in the front end.  Some endpoints will need to be returned for the data viz dropdown while some need to come down for the users list.  Other query_sets are used by other things that should not be displayed in either of those ui scenarios.

This is a more rigorous way to handle the naming convention filtering idea that we touched upon last night on hangouts.

**Comment by riley** [comment]
Categories would be fine with me as long as the whole document is returned. I understand that it's possible (likely) that users will be making tons of these things.

**Comment by ardan-bkennedy** [comment]
Done
