### ISSUE TITLE
Adds Tags to Set Documents

### ISSUE THREAD

**Issue by ardan-bkennedy** [coralproject/xenia#55]
**Challenge**: Add tags to the Set documents that can be used for filtering.

**Solution**:  tags["cat1", "item1"]
A way to provide and filter on multiple items.

**Comment by jde** [comment]
Also expose an endpoint that returns the full information about the query_sets for a given tag.

```
.../queries?tag=cheese
```
or even better
```
.../queries/tag/cheese
```
