### ISSUE TITLE
CORS not working on remote xenia

### ISSUE THREAD

**Issue by riley** [coralproject/xenia#58]
Since I changed the front end to point at the remote server today instead of `localhost`, CORS is no longer working.

## How to reproduce

1. Open Postman
2. Make an `OPTIONS` request to the remote host
  - requests to `/1.0/query` give a `200` status but no response.
  - requests to `/` give a `404`and a `404 page not found` response.

It's definitely possible that I'm not understanding how CORS is supposed to work, but I'm getting this in the Chrome dev tools as well.

```
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by ardan-bkennedy** [comment]
@riley @jde @edefikh That is odd. Let me look into that header variable.

**Comment by ardan-bkennedy** [comment]
@riley @jde This route
> requests to / give a 404and a 404 page not found response.

Does not exist.

@edefikh  Is there a reverse proxy maybe fronting the services?

**Comment by ardan-bkennedy** [comment]
@riley @jde @edefikh  I ran Postman and it appears the headers for the OPTIONS call is correct. It appears a good version of Xenia is running. I am very confused.

**Comment by ardan-bkennedy** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

I am wondering if this

> Content-Type: text/plain

is our problem. I am setting this to

> application/json

On the response to the CORS OPTIONS request?

**Comment by ardan-bkennedy** [comment]
@riley When you have a moment. Let's update the /etc/hosts file and add a record on your local machine

127.0.0.1   www.example.com

This way we are accessing Xenia via a domain name.

Then let's play with the settings. I think after reading that document, there are a few things we can try.

**Comment by ardan-bkennedy** [comment]
@riley Please let me know if this is still an issue?

http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&client_headers=Authorization%3A%20Basic%20NmQ3MmU2ZGQtOTNkMC00NDEzLTliNGMtODU0NmQ0ZDM1MTRlOlBDeVgvTFRHWjhOdGZWOGVReXZObkpydm4xc2loQk9uQW5TNFpGZGNFdnc9&server_url=http%3A%2F%2F52.23.218.253%3A4000%2F1.0%2Fquery%2Fcomments_per_day&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by riley** [comment]
I think what's happening is that an `OPTIONS` request on *any* route needs to respond with the proper headers. I thought it would just be `/`, but that doesn't seem to be the case. I think Chrome is trying to make this request:
![options](https://cloud.githubusercontent.com/assets/282503/12423541/9f87fff6-be91-11e5-9797-c9bfd8180984.png)

**Comment by ardan-bkennedy** [comment]
I know your problem. That route was changed. 

Try. /1.0/exec/name?query

I am sorry, I tried to communicate that a few different way unsuccessfully.

**Comment by ardan-bkennedy** [comment]
I have an issue to provide custom routes but in the meantime I felt this route change was more consistent with the current API.

**Comment by riley** [comment]
ah, derp. pebkac error then. Thanks for being patient with us.
