### ISSUE TITLE
Logging facilities

### ISSUE THREAD

**Issue by edefikh** [coralproject/xenia#59]
I would like to understand a way to establish loggging facilities in Xenia. Suggest mode of logging via stdout can be used in debug mode when application is running in foreground, in production mode it should be daemonized and have logging directed to syslog or files.

**Comment by ardan-bkennedy** [comment]
Services should only be writing logs to stdout. Log packages should not be dictating how logging streams are processed. I can ask Brian Knox from Digital Ocean if he has time to talk with the group about this. His focus at DO is logging and taking stdout streams from every single customer and helping them manage this.

**Comment by influx6** [comment]
This would definately be interesting to see how DO do it with stdout. Sounds good.

**Comment by ardan-bkennedy** [comment]
Brian is going to tell us what I have already stated. We should to be using [rsyslogd](http://www.rsyslog.com/) and [logrotate](https://www.loggly.com/docs/log-rotate) to start.

Here is another article that might help.
http://www.tecmint.com/manage-linux-system-logs-using-rsyslogd-and-logrotate/

Brian loves to help people so maybe we can get some of his time to show Eugene how to set this up properly? Just needs @jde approval before I reach out to him.

**Comment by jde** [comment]
This looks a lot like what the NIH inspired scripts that I've worked with in the past have done.  @edefikh, what do you think of this approach?

**Comment by jde** [comment]
We're going with the strategy that all programs write to stdout.

This allows us to see it easily on dev, or pipe to a file
Or use something like rsyslog/logrotate to handle on servers.
