### ISSUE TITLE
Remove use of strings for commands

### ISSUE THREAD

**Issue by ardan-bkennedy** [coralproject/xenia#69]
We want to start using a JSON document as the interface instead of the strings.

From
```
Scripts     []string
```

To
```
Scripts     map[string]interface{}
```

This will allow working with raw Sets easier.

**Comment by ardan-bkennedy** [comment]
HIT A WALL
What if you want to use variable substitution on an integer value

`{"field": #variable_name#}`  This is what we can do today

Now Maybe we do this

`{"field": "#number:variable_name#"}`
`{"field": "#string:variable_name#"}`
`{"field": "#date:variable_name#"}`
`{"field": "#objid:variable_name#"}`(edited)

We can also remove the Has Fields from the Set document.

**Comment by jde** [comment]
I like this approach as it makes typing more explicit.  This also gives our tooling the ability to inject ObjectID() and ISODate() wrappers around the values as they are inserted into mongo.  

I like the concept of Xenia owning the task of adding the function wrappers as the consumer shouldn't have to understand anything about mongo, only that we are looking for a date or id value.

**Comment by ardan-bkennedy** [comment]
@jde @riley  I believe this is done. If there are bugs we will open new issues.

**Comment by riley** [comment]
so great!
