### ISSUE TITLE
Add indexing to query_sets

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#73]
__Challenge__: Each query set will require one or more indexes to run efficiently.  

__Solution__: Add indexing to query_set objects.  The indexes field should accept an array of indexes.  As far as it is possible, the indexes should conform to the [syntax and feature set of mongo itself](https://docs.mongodb.org/manual/reference/method/db.collection.createIndex/#db.collection.createIndex) as opposed to the api of the mgo driver.

__Notes__
* Users need to understand that creating an index on a large collection is a costly operation that takes time and server resources.  They should also understand the background option.
* Principles of index design should be practiced considering all the indexes across all queries together.  Redundant indexes could hurt write times.

**Comment by ardan-bkennedy** [comment]
@jde I think the call to ensure should be done on the upsert. I don't want to spend time when executing a query. Thoughts.

**Comment by jde** [comment]
Agreed.  On Upsert is the appropriate time to do this.  One minor issue will be that if a new index is added to a large table, the request may take minutes or more to complete.  Two behaviors:

* the response will not be sent to the client until the index is complete, or 
* the response returns before the index is complete, but the query will remain unusable until the index actually completes.

Best solution:

When indexing is begun, xenia writes to the output buffer what it happening and flushes it to the client, using https://golang.org/pkg/net/http/#Flusher

In this solution, if, say, we had 4 indexes being added to a large collection, the response would flush 8 times: once for each index start and once for each index completion.

Is this feasible?  If it is overkill or introduces other issues, simply waiting until indexes finish would suffice.

**Comment by ardan-bkennedy** [comment]
I would create a goroutine to perform the ensure and return back to the user ASAP. I would also compare the index for changes before running it again. I think we add an /index route to ensure indexes on demand.

**Comment by ardan-bkennedy** [comment]
After coding this for a day I think it is a very bad idea to call ensure inside the same request for executing query sets. This could result in multiple calls to MongoDB before you even execute a query. If queries are running, this will affect performance if the index is new.

I will write a new package called index with its own collection and CRUD api. The from the cli tooling and web service present support for this. When we build the dev tooling, this can be utilized to ensure indexes. We can use the cli tooling in the meantime.

**Comment by jde** [comment]
I agree the basic crud index functionality is fundamental.  Overall, here's what I'd like to achieve:

1) Each query_set is packaged with the indexes it needs so devs can maintain index requirements right along with the queries that use them.
2) We have a trigger to ensure that all indexes for an individual query sets are created.  It would also be nice to have an "ensure all" trigger that loops all queries (much like the cmd tool's upsert a directory.) 

This way devs can focus on maintaining indexing requirements at a granular level but we decouple the expensive create operation so it can be run at an appropriate time.

**Comment by ardan-bkennedy** [comment]
One problem with this is some query sets may need the same indexes so you end up having people adding them twice or in different order. I think that will be a problem eventually
.
Maybe it needs to be reversed. The index is the key and we can attach which query sets use a particular index. Then if someone enters it again, we can find it and just add the query set to the list.

Too many indexes is going to hurt us as well. We need an understand of the indexes being created at a macro level. This might indicate problems with the data that we will want to change.

From a UI perspective have an Index Management tool and ways to show/graph the existing indexes and which query sets are using them. So you can't add an index without assigning it to at least one query set. If that query set is remove, we could remove indexes as well.

**Comment by ardan-bkennedy** [comment]
Indexes have been added to the query set
```
{
   "name":"QTEST_O_basic",
   "desc":"",
   "enabled":true,
   "params":[],
   "queries":[
      {
         "name":"Basic",
         "type":"pipeline",
         "collection":"test_xenia_data",
         "return":true,
		 "indexes": [
			{"key": ["station_id"], "unique": true} 
		 ],
         "commands":[
            {"$match": {"station_id" : "42021"}},
            {"$project": {"_id": 0, "name": 1}}
         ]
      }
   ]
}
```

The cli tool under query now has an index command. Supply the set name
```
query index -n user_advice
```

A new route as been added to ensure the index as well
```
PUT  :   /1.0/index/:name
```
