### ISSUE TITLE
figure out the best way to host front-end js in xenia

### ISSUE THREAD

**Issue by riley** [coralproject/xenia#81]
## What?

We're running with the assumption that the JS+CSS+HTML bundle is going to be served from Xenia instead of living on its own server. There are a couple of requirements for our UI:

1. Token/session storage for GitHub auth (or whataver we use).
2. A way to quickly put our changes live without having to pester Bill.
3. storing config of charts. Charts will be deep linkable, but do we want to have the ability to save chart configs inside the app instead of just bookmarks?.

**Comment by ardan-bkennedy** [comment]
Can we talk about what these front end requirements are. If this is front end code for the Xenia development tools I think for sure it belongs here.  If we are talking about front end components for a client that is leveraging Xenia, it might belong inside its own project.

**Comment by riley** [comment]
I think in the short term, we wanted to avoid having a separate server for Cay. Currently, all the assets are bundled into one javascript file, so I would just need to serve that and an `index.html` file.

Eventually when we serve the comments as their own platform, all this will be a separate node instance, but for now we just need some way to have a staging environment for everyone to see what Colin and I have been up to this whole time.

**Comment by riley** [comment]
@jde thoughts?

**Comment by ardan-bkennedy** [comment]
@riley I can do that easily from Xenia. Can you send me over Slack the initial code file. I will get it working and then you will have access to push changes.

**Comment by jde** [comment]
Let's hold off on hosting static files in the Xena repo.  I intend to start a Repo named Coral that contains Go code that will build Xenia, Pillar and a static file server together into one binary.  Until then we can stick with a static file hose like S3

**Comment by ardan-bkennedy** [comment]
Oops. I coded that in a couple of hours and it is there now. What I have done won't prevent what you are doing.  That being said, unless we are all using the same router and expose the endpoints in a way that you can register all of them together in your new program, you can't do what you want to.
