### ISSUE TITLE
Cache not invalidated on upsert

### ISSUE THREAD

**Issue by jde** [coralproject/xenia#82]
When updating query_sets we are seeing changes in the database but the query that is executed does not change.  This is true via the cmd tool and the api.

For example, at the moment, the query shown here:
http://10.0.1.84:4000/1.0/query/comment_timeseries_iso
is an old version 

The query executed like this:
http://10.0.1.84:4000/1.0/exec/comment_timeseries_iso?start=2013-01-01&end=2014-02-01&duration=week&target=total
executes the old version

The listing for that same query here:
http://10.0.1.84:4000/1.0/query
is the new version
and the actual document in the database is the new version

It is my assumption that the new caching technology is not invalidating the cache despite this line appearing to do so:
https://github.com/coralproject/xenia/blob/master/pkg/query/query.go#L84

Please resolve asap as this is blocking development.

Thanks!

**Comment by ardan-bkennedy** [comment]
Ugh.  I tested that. I just got on my plane. The upset call is supposed to flush the cache and then the next get retrieves it. I land 2am ET. I will have it fixed before you wake up

Sincerely,
Bill Kennedy

**Comment by ardan-bkennedy** [comment]
I looked at the Flush code, it replaces the internal map. Wondering two things. 

1) We are running on multiple servers?
2) There was an error so the code did not get hit. 

You did say you checked the database.

**Comment by ardan-bkennedy** [comment]
Ohhhhhh.  I know what the problem is. Ugh!!

The cli tooling can't affect the internal cache of the web service. 

Caching is very important and I don't want to remove it or use an external service. 

I will create an endpoint to invalidate all the caches you can call and/or the cli tooling can call as well.

**Comment by ardan-bkennedy** [comment]
I think what is best is to allow the cli tooling to talk to the web service directly. I will add a new configuration variable for the url to the web service. When it is set, it will be used instead of hitting the DB directly.

**Comment by ardan-bkennedy** [comment]
@jde, @colinmegill and @riley 

Add these env variables to your config.
export XENIA_WEB_HOST=10.0.1.84:4000
export XENIA_WEB_AUTH=// Use the Basic token you have today.

Once you source these, the cli tool will use the web api instead of hitting the DB directly. This will resolve the cache issue.

**Comment by jde** [comment]
This is good methodology.  I agree that we don't want to start adding the complexity of an external cache.

I validated that the cli upserts through the web api invalidates the cache as expected.

Thanks for the quick response!
