### ISSUE TITLE
Invalid JSON returned from some queries

### ISSUE THREAD

**Issue by riley** [coralproject/xenia#92]
## What?

I tried executing a pre-existing query `comment_timeseries_iso`. Most of the time it returns valid JSON, but if I give the param `target=asset`, I get back invalid json. Here is the offending url:

```
http://10.0.1.84:4000/1.0/exec/comment_timeseries_iso?start=2013-01-01&end=2013-02-01&duration=month&target=asset
```

If you Cmd+F for `(MISSING)`, you'll see 4 results and one that's randomly outside any strings.

**Comment by jde** [comment]
Here's the offending part of the response:

```
"target_doc":{"_id":"5679a663e19ac8521731f3b7","metadata":{"authors":[{"id":0,"name":"THE NEW YORK TIMES","title_case_name":"The New York Times","twitter":"","twitter_name":""}],"headline":"Daily Report: A Million Users Desert BlackBerry, and Revenue Falls 48%!"(MISSING),"publicationdate":1356097179,"publicationdateiso":"0001-01-01T00:00:00Z","section":{"content":"technology","display_name":"Technology","keywords":[]}
```

Note that there's ```(MISSING)``` appended after the headline string.

**Comment by ardan-bkennedy** [comment]
This will be my first priority in the morning.

**Comment by ardan-bkennedy** [comment]
comment_timeseries
{"_id": ObjectId("56a759cae19ac80d14ab7ab6")}

This is what you are seeing
"headline" : "Citadel Posted 25%!R(MISSING)eturn Last Year, Beating Industry Again"

This is what is in the DB
"headline" : "Citadel Posted 25% Return Last Year, Beating Industry Again", 

I will look into this, it seems the % is being treaded in some sort of "format" operation but at this point I have no idea where or how.

**Comment by ardan-bkennedy** [comment]
I know what the BUG is. The data is being transformed from the HTML side. I just ran everything from the cli tool hitting the DB and the data was clean.

**Comment by ardan-bkennedy** [comment]
Fixed !!!
